spring:
  profiles:
    active: default
  config:
    import: application-prod.yml
  application:
    name: fsbank
  datasource:
    url: jdbc:h2:file:./user-test-db
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:30m}