spring:
  config:
    activate:
      on-profile: prod
  application:
    name: fsbank
  datasource:
    url: jdbc:h2:mem:user-test-db
    username: sa
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: false
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:15m}